#!/bin/bash
# Set up an environment
#
# Variables are held in /private/form-settings-variables-$ENV, so they are
# environment specific.
# ------------------------------------------------------------------------------
if [ -z "$1" ]
then
    echo "You must specify an environment: \"staging\" or \"production\"."; exit
else
    ENV=$1
fi

# Set path to the common config file for this environment
THIS=$(readlink -f ${BASH_SOURCE[0]})
CURRENT_PARENT_DIR=$(dirname $THIS)
CONFIG_FILE="$CURRENT_PARENT_DIR/config/${ENV}/variables-${ENV}"

# Collect User Input
echo "Enter the username for the remote ${ENV} server:"
read USERNAME
echo "Enter the IP address of the remote ${ENV} server:"
read IP
echo "Enter the base path for your LOCAL project (/var/www/html/site.dev):"
read LOCAL_BASEPATH
echo "Enter the base path for your REMOTE project on the ${ENV} server:"
read REMOTE_BASEPATH
echo "Enter the SSH port used to rsync with the remote ${ENV} server:"
read PORT

#
# Output to file
read -r -d '' CONFIG_CONTENT << EOF
#!/bin/bash
# Project specific common variables: ${ENV}
# DO NOT COMMIT
# ------------------------------------------------------------------------------
USERNAME="${USERNAME}"
IP="${IP}"
BASE_SRC="${LOCAL_BASEPATH}"
BASE_DEST="${REMOTE_BASEPATH}"
PORT="${PORT}"

# Array of common rsync options
OPT=(--progress -a -v -rz)
EOF

mkdir -p ${CURRENT_PARENT_DIR}/config/${ENV} && touch ${CONFIG_FILE}
# See http://unix.stackexchange.com/a/19708
sh -c "printf '%s' '$CONFIG_CONTENT' > ${CONFIG_FILE}"
