#!/bin/bash

# Project specific common variables: staging
# ------------------------------------------------------------------------------
USERNAME="username"
IP="X.X.X.X"
BASE_SRC="/var/www/html/local-project-path"
BASE_DEST="/var/www/html/remote-project-path"
PORT="1111"

# Array of common rsync options
OPT=(--progress -a -v -rz)
