#!/bin/bash

# Project specific Variables
# ------------------------------------------------------------------------------
# Set directory and include dependencies
THIS=$(readlink -f ${BASH_SOURCE[0]})
CURRENT_DIR=$(dirname $THIS)
. "$CURRENT_DIR/common-variables-$ENV"

# Set paths
RELATIVE_LOCAL_PATH="relative/path/to/form-config"
SRC="${BASE_SRC}/${RELATIVE_LOCAL_PATH}"
RELATIVE_REMOTE_PATH="config/form-config"
DEST="${BASE_DEST}/${RELATIVE_REMOTE_PATH}"
LOG="${PROJECT_DIR}/logs/staging-form-settings-log"
